export * from "./navbar/Navbar";
export * from "./hero/HeroComponent";
export * from "./producto/Producto";
export * from "./servicios/Servicios";
export * from "./soluciones/Soluciones";
export * from "./conecta/Conecta";
export * from "./footer/Footer";
export * from "./tecnologia/Tecnologia";
export * from "./pageTransitions/PageTransition";
